name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
        
    - name: Install client dependencies
      run: cd client && npm ci
      
    - name: Build client
      run: cd client && npm run build
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install Capacitor
      run: cd client && npm install @capacitor/cli @capacitor/core @capacitor/android
      
    - name: Configure Capacitor and Build Android
      run: |
        cd client
        # Remove any existing config files
        rm -f capacitor.config.*
        # Create JSON config
        echo '{
          "appId": "com.goodboycat.heavyapp",
          "appName": "Heavy App",
          "webDir": "dist",
          "server": {
            "androidScheme": "https"
          }
        }' > capacitor.config.json
        # Add Android platform
        npx cap add android
        npx cap sync
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: heavy-app-apk
        path: client/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

  # Separate job for tests (optional, won't block APK build)
  test:
    runs-on: ubuntu-latest
    if: false  # Disabled for now
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: cd client && npm ci
    - name: Run tests
      run: cd client && npm run test
